// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_add_matrix_add,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.769000,HLS_SYN_LAT=102,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=28,HLS_SYN_LUT=230,HLS_VERSION=2024_1}" *)

module matrix_add (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        B_address0,
        B_ce0,
        B_q0,
        C_address0,
        C_ce0,
        C_we0,
        C_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] A_address0;
output   A_ce0;
input  [31:0] A_q0;
output  [6:0] B_address0;
output   B_ce0;
input  [31:0] B_q0;
output  [6:0] C_address0;
output   C_ce0;
output   C_we0;
output  [31:0] C_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln6_fu_223_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln8_1_fu_199_p1;
reg   [63:0] zext_ln8_1_reg_272;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln7_fu_217_p2;
reg   [0:0] icmp_ln7_reg_287;
reg   [0:0] icmp_ln6_reg_292;
reg   [0:0] ap_phi_mux_icmp_ln74_phi_fu_110_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [6:0] indvar_flatten1_fu_56;
wire   [6:0] add_ln6_1_fu_211_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten1_load;
reg   [3:0] i2_fu_60;
wire   [3:0] i_fu_155_p3;
reg   [3:0] ap_sig_allocacmp_i2_load;
reg   [3:0] j3_fu_64;
wire   [3:0] j_fu_205_p2;
reg   [3:0] ap_sig_allocacmp_j3_load;
reg    A_ce0_local;
reg    B_ce0_local;
reg    C_we0_local;
wire   [31:0] add_ln8_fu_244_p2;
reg    C_ce0_local;
wire   [3:0] add_ln6_fu_141_p2;
wire   [4:0] tmp_1_fu_171_p3;
wire   [6:0] tmp_fu_163_p3;
wire   [6:0] zext_ln7_fu_179_p1;
wire   [3:0] select_ln6_fu_147_p3;
wire   [6:0] add_ln7_1_fu_183_p2;
wire   [6:0] zext_ln8_fu_189_p1;
wire   [6:0] add_ln8_1_fu_193_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_224;
reg    ap_condition_77;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 indvar_flatten1_fu_56 = 7'd0;
#0 i2_fu_60 = 4'd0;
#0 j3_fu_64 = 4'd0;
#0 ap_done_reg = 1'b0;
end

matrix_add_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_77)) begin
        i2_fu_60 <= i_fu_155_p3;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_77)) begin
    indvar_flatten1_fu_56 <= add_ln6_1_fu_211_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_77)) begin
    j3_fu_64 <= j_fu_205_p2;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln6_reg_292 <= icmp_ln6_fu_223_p2;
        zext_ln8_1_reg_272[6 : 0] <= zext_ln8_1_fu_199_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln7_reg_287 <= icmp_ln7_fu_217_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_ce0_local = 1'b1;
    end else begin
        A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        B_ce0_local = 1'b1;
    end else begin
        B_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_ce0_local = 1'b1;
    end else begin
        C_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_we0_local = 1'b1;
    end else begin
        C_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln6_fu_223_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_224)) begin
            ap_phi_mux_icmp_ln74_phi_fu_110_p4 = icmp_ln7_reg_287;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln74_phi_fu_110_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln74_phi_fu_110_p4 = icmp_ln7_reg_287;
        end
    end else begin
        ap_phi_mux_icmp_ln74_phi_fu_110_p4 = icmp_ln7_reg_287;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i2_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i2_load = i2_fu_60;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten1_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten1_load = indvar_flatten1_fu_56;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j3_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j3_load = j3_fu_64;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = zext_ln8_1_fu_199_p1;

assign A_ce0 = A_ce0_local;

assign B_address0 = zext_ln8_1_fu_199_p1;

assign B_ce0 = B_ce0_local;

assign C_address0 = zext_ln8_1_reg_272;

assign C_ce0 = C_ce0_local;

assign C_d0 = add_ln8_fu_244_p2;

assign C_we0 = C_we0_local;

assign add_ln6_1_fu_211_p2 = (ap_sig_allocacmp_indvar_flatten1_load + 7'd1);

assign add_ln6_fu_141_p2 = (ap_sig_allocacmp_i2_load + 4'd1);

assign add_ln7_1_fu_183_p2 = (tmp_fu_163_p3 + zext_ln7_fu_179_p1);

assign add_ln8_1_fu_193_p2 = (add_ln7_1_fu_183_p2 + zext_ln8_fu_189_p1);

assign add_ln8_fu_244_p2 = (B_q0 + A_q0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_224 = ((icmp_ln6_reg_292 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_77 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign i_fu_155_p3 = ((ap_phi_mux_icmp_ln74_phi_fu_110_p4[0:0] == 1'b1) ? add_ln6_fu_141_p2 : ap_sig_allocacmp_i2_load);

assign icmp_ln6_fu_223_p2 = ((ap_sig_allocacmp_indvar_flatten1_load == 7'd99) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_217_p2 = ((j_fu_205_p2 == 4'd10) ? 1'b1 : 1'b0);

assign j_fu_205_p2 = (select_ln6_fu_147_p3 + 4'd1);

assign select_ln6_fu_147_p3 = ((ap_phi_mux_icmp_ln74_phi_fu_110_p4[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_j3_load);

assign tmp_1_fu_171_p3 = {{i_fu_155_p3}, {1'd0}};

assign tmp_fu_163_p3 = {{i_fu_155_p3}, {3'd0}};

assign zext_ln7_fu_179_p1 = tmp_1_fu_171_p3;

assign zext_ln8_1_fu_199_p1 = add_ln8_1_fu_193_p2;

assign zext_ln8_fu_189_p1 = select_ln6_fu_147_p3;

always @ (posedge ap_clk) begin
    zext_ln8_1_reg_272[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //matrix_add
