// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bubbleSort_bubbleSort_Pipeline_VITIS_LOOP_16_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        indvars_iv6,
        arr_address0,
        arr_ce0,
        arr_we0,
        arr_d0,
        arr_q0,
        arr_address1,
        arr_ce1,
        arr_we1,
        arr_d1,
        arr_q1
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] indvars_iv6;
output  [3:0] arr_address0;
output   arr_ce0;
output   arr_we0;
output  [31:0] arr_d0;
input  [31:0] arr_q0;
output  [3:0] arr_address1;
output   arr_ce1;
output   arr_we1;
output  [31:0] arr_d1;
input  [31:0] arr_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln16_fu_85_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state2;
wire   [3:0] add_ln19_fu_91_p2;
reg   [3:0] add_ln19_reg_127;
reg   [3:0] arr_addr_reg_132;
reg   [3:0] arr_addr_1_reg_137;
wire   [63:0] zext_ln16_fu_97_p1;
wire   [63:0] zext_ln19_fu_102_p1;
reg   [3:0] j_fu_40;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_1;
reg    arr_ce1_local;
reg   [3:0] arr_address1_local;
reg    arr_ce0_local;
reg   [3:0] arr_address0_local;
reg    arr_we1_local;
wire   [0:0] icmp_ln19_fu_107_p2;
reg    arr_we0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 j_fu_40 = 4'd0;
#0 ap_done_reg = 1'b0;
end

bubbleSort_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        j_fu_40 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        j_fu_40 <= add_ln19_reg_127;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln19_reg_127 <= add_ln19_fu_91_p2;
        arr_addr_1_reg_137 <= zext_ln19_fu_102_p1;
        arr_addr_reg_132 <= zext_ln16_fu_97_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln16_fu_85_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_j_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_40;
    end
end

always @ (*) begin
    if (((icmp_ln19_fu_107_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        arr_address0_local = arr_addr_1_reg_137;
    end else if (((icmp_ln16_fu_85_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        arr_address0_local = zext_ln19_fu_102_p1;
    end else begin
        arr_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln19_fu_107_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        arr_address1_local = arr_addr_reg_132;
    end else if (((icmp_ln16_fu_85_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        arr_address1_local = zext_ln16_fu_97_p1;
    end else begin
        arr_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln19_fu_107_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln16_fu_85_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arr_ce0_local = 1'b1;
    end else begin
        arr_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln19_fu_107_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln16_fu_85_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)))) begin
        arr_ce1_local = 1'b1;
    end else begin
        arr_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln19_fu_107_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        arr_we0_local = 1'b1;
    end else begin
        arr_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln19_fu_107_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        arr_we1_local = 1'b1;
    end else begin
        arr_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln16_fu_85_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln19_fu_91_p2 = (ap_sig_allocacmp_j_1 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign arr_address0 = arr_address0_local;

assign arr_address1 = arr_address1_local;

assign arr_ce0 = arr_ce0_local;

assign arr_ce1 = arr_ce1_local;

assign arr_d0 = arr_q1;

assign arr_d1 = arr_q0;

assign arr_we0 = arr_we0_local;

assign arr_we1 = arr_we1_local;

assign icmp_ln16_fu_85_p2 = ((ap_sig_allocacmp_j_1 == indvars_iv6) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_107_p2 = (($signed(arr_q1) > $signed(arr_q0)) ? 1'b1 : 1'b0);

assign zext_ln16_fu_97_p1 = ap_sig_allocacmp_j_1;

assign zext_ln19_fu_102_p1 = add_ln19_fu_91_p2;

endmodule //bubbleSort_bubbleSort_Pipeline_VITIS_LOOP_16_2
