-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bubbleSort is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    arr_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arr_ce0 : OUT STD_LOGIC;
    arr_we0 : OUT STD_LOGIC;
    arr_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arr_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    arr_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    arr_ce1 : OUT STD_LOGIC;
    arr_we1 : OUT STD_LOGIC;
    arr_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    arr_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of bubbleSort is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "bubbleSort_bubbleSort,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p-fsga2577-2-e,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.278000,HLS_SYN_LAT=301,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=35,HLS_SYN_LUT=206,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal indvars_iv6_load_reg_113 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_start : STD_LOGIC;
    signal grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_done : STD_LOGIC;
    signal grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_idle : STD_LOGIC;
    signal grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_ready : STD_LOGIC;
    signal grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_ce0 : STD_LOGIC;
    signal grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_we0 : STD_LOGIC;
    signal grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_ce1 : STD_LOGIC;
    signal grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_we1 : STD_LOGIC;
    signal grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln13_fu_64_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_fu_36 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal i_2_fu_70_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvars_iv6_fu_40 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln13_fu_80_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bubbleSort_bubbleSort_Pipeline_VITIS_LOOP_16_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        indvars_iv6 : IN STD_LOGIC_VECTOR (3 downto 0);
        arr_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        arr_ce0 : OUT STD_LOGIC;
        arr_we0 : OUT STD_LOGIC;
        arr_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        arr_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        arr_ce1 : OUT STD_LOGIC;
        arr_we1 : OUT STD_LOGIC;
        arr_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44 : component bubbleSort_bubbleSort_Pipeline_VITIS_LOOP_16_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_start,
        ap_done => grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_done,
        ap_idle => grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_idle,
        ap_ready => grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_ready,
        indvars_iv6 => indvars_iv6_load_reg_113,
        arr_address0 => grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_address0,
        arr_ce0 => grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_ce0,
        arr_we0 => grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_we0,
        arr_d0 => grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_d0,
        arr_q0 => arr_q0,
        arr_address1 => grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_address1,
        arr_ce1 => grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_ce1,
        arr_we1 => grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_we1,
        arr_d1 => grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_d1,
        arr_q1 => arr_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln13_fu_64_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_ready = ap_const_logic_1)) then 
                    grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_36_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_36 <= ap_const_lv4_0;
            elsif (((icmp_ln13_fu_64_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_fu_36 <= i_2_fu_70_p2;
            end if; 
        end if;
    end process;

    indvars_iv6_fu_40_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvars_iv6_fu_40 <= ap_const_lv4_F;
            elsif (((icmp_ln13_fu_64_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                indvars_iv6_fu_40 <= add_ln13_fu_80_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                indvars_iv6_load_reg_113 <= indvars_iv6_fu_40;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_done, icmp_ln13_fu_64_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln13_fu_64_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln13_fu_80_p2 <= std_logic_vector(unsigned(indvars_iv6_fu_40) + unsigned(ap_const_lv4_F));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_done)
    begin
        if ((grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln13_fu_64_p2)
    begin
        if (((icmp_ln13_fu_64_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln13_fu_64_p2)
    begin
        if (((icmp_ln13_fu_64_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    arr_address0 <= grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_address0;
    arr_address1 <= grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_address1;
    arr_ce0 <= grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_ce0;
    arr_ce1 <= grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_ce1;
    arr_d0 <= grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_d0;
    arr_d1 <= grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_d1;
    arr_we0 <= grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_we0;
    arr_we1 <= grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_arr_we1;
    grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_start <= grp_bubbleSort_Pipeline_VITIS_LOOP_16_2_fu_44_ap_start_reg;
    i_2_fu_70_p2 <= std_logic_vector(unsigned(i_fu_36) + unsigned(ap_const_lv4_1));
    icmp_ln13_fu_64_p2 <= "1" when (i_fu_36 = ap_const_lv4_F) else "0";
end behav;
