-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    A_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    A_ce1 : OUT STD_LOGIC;
    A_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    B_ce0 : OUT STD_LOGIC;
    B_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    B_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    B_ce1 : OUT STD_LOGIC;
    B_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    C_ce0 : OUT STD_LOGIC;
    C_we0 : OUT STD_LOGIC;
    C_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of matrix_mult is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult_matrix_mult,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.563000,HLS_SYN_LAT=502,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=211,HLS_SYN_LUT=964,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv7_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_const_lv7_3 : STD_LOGIC_VECTOR (6 downto 0) := "0000011";
    constant ap_const_lv6_14 : STD_LOGIC_VECTOR (5 downto 0) := "010100";
    constant ap_const_lv6_1E : STD_LOGIC_VECTOR (5 downto 0) := "011110";
    constant ap_const_lv7_4 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_const_lv7_5 : STD_LOGIC_VECTOR (6 downto 0) := "0000101";
    constant ap_const_lv6_28 : STD_LOGIC_VECTOR (5 downto 0) := "101000";
    constant ap_const_lv7_32 : STD_LOGIC_VECTOR (6 downto 0) := "0110010";
    constant ap_const_lv7_6 : STD_LOGIC_VECTOR (6 downto 0) := "0000110";
    constant ap_const_lv7_7 : STD_LOGIC_VECTOR (6 downto 0) := "0000111";
    constant ap_const_lv7_3C : STD_LOGIC_VECTOR (6 downto 0) := "0111100";
    constant ap_const_lv7_46 : STD_LOGIC_VECTOR (6 downto 0) := "1000110";
    constant ap_const_lv7_8 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_const_lv7_9 : STD_LOGIC_VECTOR (6 downto 0) := "0001001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv7_5A : STD_LOGIC_VECTOR (6 downto 0) := "1011010";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv7_63 : STD_LOGIC_VECTOR (6 downto 0) := "1100011";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal icmp_ln5_fu_680_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage4 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal grp_fu_313_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_329 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal grp_fu_319_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_333 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal select_ln5_fu_364_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln5_reg_755 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal empty_6_fu_415_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_6_reg_763 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal zext_ln9_1_fu_487_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln9_1_reg_806 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln9_fu_512_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln9_reg_821 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln9_fu_538_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln9_reg_836 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln9_2_fu_608_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln9_2_reg_874 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln11_fu_659_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln11_reg_899 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln9_4_reg_904 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln6_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln6_reg_909 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln5_reg_914 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_icmp_ln64_phi_fu_306_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_cast7_fu_410_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_cast_fu_437_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln6_fu_442_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln9_3_fu_457_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast8_fu_472_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal p_cast9_fu_482_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln9_4_fu_496_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln9_5_fu_507_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast10_fu_523_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal p_cast11_fu_533_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln9_6_fu_546_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln9_7_fu_557_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast12_fu_567_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal p_cast13_fu_577_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln9_8_fu_587_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln9_9_fu_597_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast14_fu_622_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal p_cast15_fu_632_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln9_10_fu_644_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln9_11_fu_654_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_fu_696_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten1_fu_100 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln5_1_fu_668_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal i2_fu_104 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal i_fu_372_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_i2_load : STD_LOGIC_VECTOR (3 downto 0);
    signal j3_fu_108 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal j_fu_663_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_j3_load : STD_LOGIC_VECTOR (3 downto 0);
    signal A_ce1_local : STD_LOGIC;
    signal A_address1_local : STD_LOGIC_VECTOR (6 downto 0);
    signal A_ce0_local : STD_LOGIC;
    signal A_address0_local : STD_LOGIC_VECTOR (6 downto 0);
    signal B_ce1_local : STD_LOGIC;
    signal B_address1_local : STD_LOGIC_VECTOR (6 downto 0);
    signal B_ce0_local : STD_LOGIC;
    signal B_address0_local : STD_LOGIC_VECTOR (6 downto 0);
    signal C_we0_local : STD_LOGIC;
    signal sum_fu_727_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal C_ce0_local : STD_LOGIC;
    signal grp_fu_313_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_313_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_319_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_319_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln5_fu_358_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_380_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_2_fu_392_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl_fu_388_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl43_fu_400_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_404_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_cast_fu_419_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_1_fu_429_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln9_2_fu_447_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln9_8_fu_451_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_7_fu_467_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_8_fu_477_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln9_9_fu_490_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln9_10_fu_501_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_9_fu_518_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_10_fu_528_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln9_11_fu_541_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln9_12_fu_551_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_11_fu_562_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_12_fu_572_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln9_13_fu_582_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln9_14_fu_592_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln9_1_fu_602_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_13_fu_617_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_14_fu_627_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_2_cast_fu_637_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln9_15_fu_649_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln9_5_fu_710_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln9_6_fu_716_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln9_4_fu_704_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln9_7_fu_721_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln9_3_fu_700_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_635 : BOOLEAN;
    signal ap_condition_251 : BOOLEAN;
    signal ap_condition_640 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mult_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matrix_mult_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_32_1_1_U1 : component matrix_mult_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_313_p0,
        din1 => grp_fu_313_p1,
        dout => grp_fu_313_p2);

    mul_32s_32s_32_1_1_U2 : component matrix_mult_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_319_p0,
        din1 => grp_fu_319_p1,
        dout => grp_fu_319_p2);

    flow_control_loop_pipe_U : component matrix_mult_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage4,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    i2_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_251)) then
                i2_fu_104 <= i_fu_372_p3;
            end if;
        end if;
    end process;

    indvar_flatten1_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if ((ap_const_boolean_1 = ap_condition_640)) then 
                    indvar_flatten1_fu_100 <= ap_const_lv7_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                    indvar_flatten1_fu_100 <= add_ln5_1_fu_668_p2;
                end if;
            end if; 
        end if;
    end process;

    j3_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if ((ap_const_boolean_1 = ap_condition_640)) then 
                    j3_fu_108 <= ap_const_lv4_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                    j3_fu_108 <= j_fu_663_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                add_ln11_reg_899 <= add_ln11_fu_659_p2;
                icmp_ln5_reg_914 <= icmp_ln5_fu_680_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                add_ln9_2_reg_874 <= add_ln9_2_fu_608_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln9_reg_821 <= add_ln9_fu_512_p2;
                    zext_ln9_1_reg_806(3 downto 0) <= zext_ln9_1_fu_487_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    empty_6_reg_763(6 downto 1) <= empty_6_fu_415_p1(6 downto 1);
                select_ln5_reg_755 <= select_ln5_fu_364_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                icmp_ln6_reg_909 <= icmp_ln6_fu_674_p2;
                mul_ln9_4_reg_904 <= grp_fu_319_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then
                reg_329 <= grp_fu_313_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then
                reg_333 <= grp_fu_319_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                    zext_ln9_reg_836(3 downto 0) <= zext_ln9_fu_538_p1(3 downto 0);
            end if;
        end if;
    end process;
    empty_6_reg_763(0) <= '0';
    zext_ln9_1_reg_806(5 downto 4) <= "00";
    zext_ln9_reg_836(6 downto 4) <= "000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage4_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter1_stage0, ap_idle_pp0_0to0, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    A_address0 <= A_address0_local;

    A_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, tmp_1_cast_fu_437_p1, ap_block_pp0_stage1, p_cast9_fu_482_p1, ap_block_pp0_stage2, p_cast11_fu_533_p1, ap_block_pp0_stage3, p_cast13_fu_577_p1, ap_block_pp0_stage4, p_cast15_fu_632_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                A_address0_local <= p_cast15_fu_632_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                A_address0_local <= p_cast13_fu_577_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                A_address0_local <= p_cast11_fu_533_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                A_address0_local <= p_cast9_fu_482_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                A_address0_local <= tmp_1_cast_fu_437_p1(7 - 1 downto 0);
            else 
                A_address0_local <= "XXXXXXX";
            end if;
        else 
            A_address0_local <= "XXXXXXX";
        end if; 
    end process;

    A_address1 <= A_address1_local;

    A_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, p_cast7_fu_410_p1, p_cast8_fu_472_p1, ap_block_pp0_stage1, p_cast10_fu_523_p1, ap_block_pp0_stage2, p_cast12_fu_567_p1, ap_block_pp0_stage3, p_cast14_fu_622_p1, ap_block_pp0_stage4)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                A_address1_local <= p_cast14_fu_622_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                A_address1_local <= p_cast12_fu_567_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                A_address1_local <= p_cast10_fu_523_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                A_address1_local <= p_cast8_fu_472_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                A_address1_local <= p_cast7_fu_410_p1(7 - 1 downto 0);
            else 
                A_address1_local <= "XXXXXXX";
            end if;
        else 
            A_address1_local <= "XXXXXXX";
        end if; 
    end process;

    A_ce0 <= A_ce0_local;

    A_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage4_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            A_ce0_local <= ap_const_logic_1;
        else 
            A_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_ce1 <= A_ce1_local;

    A_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage4_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            A_ce1_local <= ap_const_logic_1;
        else 
            A_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_address0 <= B_address0_local;

    B_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln9_3_fu_457_p1, ap_block_pp0_stage1, zext_ln9_5_fu_507_p1, ap_block_pp0_stage2, zext_ln9_7_fu_557_p1, ap_block_pp0_stage3, zext_ln9_9_fu_597_p1, ap_block_pp0_stage4, zext_ln9_11_fu_654_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                B_address0_local <= zext_ln9_11_fu_654_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                B_address0_local <= zext_ln9_9_fu_597_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                B_address0_local <= zext_ln9_7_fu_557_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                B_address0_local <= zext_ln9_5_fu_507_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                B_address0_local <= zext_ln9_3_fu_457_p1(7 - 1 downto 0);
            else 
                B_address0_local <= "XXXXXXX";
            end if;
        else 
            B_address0_local <= "XXXXXXX";
        end if; 
    end process;

    B_address1 <= B_address1_local;

    B_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln6_fu_442_p1, ap_block_pp0_stage1, zext_ln9_4_fu_496_p1, ap_block_pp0_stage2, zext_ln9_6_fu_546_p1, ap_block_pp0_stage3, zext_ln9_8_fu_587_p1, ap_block_pp0_stage4, zext_ln9_10_fu_644_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                B_address1_local <= zext_ln9_10_fu_644_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                B_address1_local <= zext_ln9_8_fu_587_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                B_address1_local <= zext_ln9_6_fu_546_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                B_address1_local <= zext_ln9_4_fu_496_p1(7 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                B_address1_local <= zext_ln6_fu_442_p1(7 - 1 downto 0);
            else 
                B_address1_local <= "XXXXXXX";
            end if;
        else 
            B_address1_local <= "XXXXXXX";
        end if; 
    end process;

    B_ce0 <= B_ce0_local;

    B_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage4_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            B_ce0_local <= ap_const_logic_1;
        else 
            B_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    B_ce1 <= B_ce1_local;

    B_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage4_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)))) then 
            B_ce1_local <= ap_const_logic_1;
        else 
            B_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    C_address0 <= zext_ln11_fu_696_p1(7 - 1 downto 0);
    C_ce0 <= C_ce0_local;

    C_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_ce0_local <= ap_const_logic_1;
        else 
            C_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_d0 <= sum_fu_727_p2;
    C_we0 <= C_we0_local;

    C_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_we0_local <= ap_const_logic_1;
        else 
            C_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln11_fu_659_p2 <= std_logic_vector(unsigned(empty_6_reg_763) + unsigned(zext_ln9_reg_836));
    add_ln5_1_fu_668_p2 <= std_logic_vector(unsigned(indvar_flatten1_fu_100) + unsigned(ap_const_lv7_1));
    add_ln5_fu_358_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i2_load) + unsigned(ap_const_lv4_1));
    add_ln9_10_fu_501_p2 <= std_logic_vector(unsigned(zext_ln9_1_fu_487_p1) + unsigned(ap_const_lv6_1E));
    add_ln9_11_fu_541_p2 <= std_logic_vector(unsigned(zext_ln9_1_reg_806) + unsigned(ap_const_lv6_28));
    add_ln9_12_fu_551_p2 <= std_logic_vector(unsigned(zext_ln9_fu_538_p1) + unsigned(ap_const_lv7_32));
    add_ln9_13_fu_582_p2 <= std_logic_vector(unsigned(zext_ln9_reg_836) + unsigned(ap_const_lv7_3C));
    add_ln9_14_fu_592_p2 <= std_logic_vector(unsigned(zext_ln9_reg_836) + unsigned(ap_const_lv7_46));
    add_ln9_15_fu_649_p2 <= std_logic_vector(unsigned(zext_ln9_reg_836) + unsigned(ap_const_lv7_5A));
    add_ln9_1_fu_602_p2 <= std_logic_vector(unsigned(reg_333) + unsigned(grp_fu_313_p2));
    add_ln9_2_fu_608_p2 <= std_logic_vector(unsigned(add_ln9_1_fu_602_p2) + unsigned(reg_329));
    add_ln9_3_fu_700_p2 <= std_logic_vector(unsigned(add_ln9_2_reg_874) + unsigned(add_ln9_reg_821));
    add_ln9_4_fu_704_p2 <= std_logic_vector(unsigned(reg_333) + unsigned(reg_329));
    add_ln9_5_fu_710_p2 <= std_logic_vector(unsigned(grp_fu_319_p2) + unsigned(grp_fu_313_p2));
    add_ln9_6_fu_716_p2 <= std_logic_vector(unsigned(add_ln9_5_fu_710_p2) + unsigned(mul_ln9_4_reg_904));
    add_ln9_7_fu_721_p2 <= std_logic_vector(unsigned(add_ln9_6_fu_716_p2) + unsigned(add_ln9_4_fu_704_p2));
    add_ln9_8_fu_451_p2 <= std_logic_vector(unsigned(zext_ln9_2_fu_447_p1) + unsigned(ap_const_lv5_A));
    add_ln9_9_fu_490_p2 <= std_logic_vector(unsigned(zext_ln9_1_fu_487_p1) + unsigned(ap_const_lv6_14));
    add_ln9_fu_512_p2 <= std_logic_vector(unsigned(grp_fu_319_p2) + unsigned(grp_fu_313_p2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_251_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_251 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_635_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln5_reg_914, ap_block_pp0_stage0)
    begin
                ap_condition_635 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln5_reg_914 = ap_const_lv1_0));
    end process;


    ap_condition_640_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_loop_init)
    begin
                ap_condition_640 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage4_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_subdone, icmp_ln5_fu_680_p2)
    begin
        if (((icmp_ln5_fu_680_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            ap_condition_exit_pp0_iter0_stage4 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln5_reg_914, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln5_reg_914 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage4;

    ap_phi_mux_icmp_ln64_phi_fu_306_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln6_reg_909, ap_loop_init, ap_condition_635)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_635)) then 
                ap_phi_mux_icmp_ln64_phi_fu_306_p4 <= icmp_ln6_reg_909;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln64_phi_fu_306_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln64_phi_fu_306_p4 <= icmp_ln6_reg_909;
            end if;
        else 
            ap_phi_mux_icmp_ln64_phi_fu_306_p4 <= icmp_ln6_reg_909;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i2_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, i2_fu_104)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i2_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i2_load <= i2_fu_104;
        end if; 
    end process;


    ap_sig_allocacmp_j3_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, j3_fu_108)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j3_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_j3_load <= j3_fu_108;
        end if; 
    end process;

    empty_10_fu_528_p2 <= std_logic_vector(unsigned(empty_6_reg_763) + unsigned(ap_const_lv7_5));
    empty_11_fu_562_p2 <= std_logic_vector(unsigned(empty_6_reg_763) + unsigned(ap_const_lv7_6));
    empty_12_fu_572_p2 <= std_logic_vector(unsigned(empty_6_reg_763) + unsigned(ap_const_lv7_7));
    empty_13_fu_617_p2 <= std_logic_vector(unsigned(empty_6_reg_763) + unsigned(ap_const_lv7_8));
    empty_14_fu_627_p2 <= std_logic_vector(unsigned(empty_6_reg_763) + unsigned(ap_const_lv7_9));
    empty_6_fu_415_p1 <= empty_fu_404_p2(7 - 1 downto 0);
    empty_7_fu_467_p2 <= std_logic_vector(unsigned(empty_6_reg_763) + unsigned(ap_const_lv7_2));
    empty_8_fu_477_p2 <= std_logic_vector(unsigned(empty_6_reg_763) + unsigned(ap_const_lv7_3));
    empty_9_fu_518_p2 <= std_logic_vector(unsigned(empty_6_reg_763) + unsigned(ap_const_lv7_4));
    empty_fu_404_p2 <= std_logic_vector(unsigned(p_shl_fu_388_p1) + unsigned(p_shl43_fu_400_p1));

    grp_fu_313_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, B_q0, B_q1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3, ap_block_pp0_stage4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_313_p0 <= B_q0;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_313_p0 <= B_q1;
        else 
            grp_fu_313_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_313_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, A_q0, A_q1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3, ap_block_pp0_stage4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_313_p1 <= A_q0;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_313_p1 <= A_q1;
        else 
            grp_fu_313_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_319_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, B_q0, B_q1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3, ap_block_pp0_stage4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_319_p0 <= B_q1;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_319_p0 <= B_q0;
        else 
            grp_fu_319_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_319_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, A_q0, A_q1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3, ap_block_pp0_stage4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_319_p1 <= A_q1;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_319_p1 <= A_q0;
        else 
            grp_fu_319_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    i_fu_372_p3 <= 
        add_ln5_fu_358_p2 when (ap_phi_mux_icmp_ln64_phi_fu_306_p4(0) = '1') else 
        ap_sig_allocacmp_i2_load;
    icmp_ln5_fu_680_p2 <= "1" when (indvar_flatten1_fu_100 = ap_const_lv7_63) else "0";
    icmp_ln6_fu_674_p2 <= "1" when (j_fu_663_p2 = ap_const_lv4_A) else "0";
    j_fu_663_p2 <= std_logic_vector(unsigned(select_ln5_reg_755) + unsigned(ap_const_lv4_1));
    p_cast10_fu_523_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_9_fu_518_p2),64));
    p_cast11_fu_533_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_10_fu_528_p2),64));
    p_cast12_fu_567_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_11_fu_562_p2),64));
    p_cast13_fu_577_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_12_fu_572_p2),64));
    p_cast14_fu_622_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_13_fu_617_p2),64));
    p_cast15_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_14_fu_627_p2),64));
    p_cast7_fu_410_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_fu_404_p2),64));
    p_cast8_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_7_fu_467_p2),64));
    p_cast9_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_8_fu_477_p2),64));
    p_shl43_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_392_p3),8));
    p_shl_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_380_p3),8));
    select_ln5_fu_364_p3 <= 
        ap_const_lv4_0 when (ap_phi_mux_icmp_ln64_phi_fu_306_p4(0) = '1') else 
        ap_sig_allocacmp_j3_load;
    sum_fu_727_p2 <= std_logic_vector(unsigned(add_ln9_7_fu_721_p2) + unsigned(add_ln9_3_fu_700_p2));
    tmp_1_cast_fu_437_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_429_p3),64));
    tmp_1_fu_429_p3 <= (tmp_cast_fu_419_p4 & ap_const_lv1_1);
    tmp_2_cast_fu_637_p3 <= (ap_const_lv3_5 & select_ln5_reg_755);
    tmp_2_fu_392_p3 <= (i_fu_372_p3 & ap_const_lv1_0);
    tmp_cast_fu_419_p4 <= empty_fu_404_p2(6 downto 1);
    tmp_fu_380_p3 <= (i_fu_372_p3 & ap_const_lv3_0);
    zext_ln11_fu_696_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_reg_899),64));
    zext_ln6_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln5_fu_364_p3),64));
    zext_ln9_10_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_cast_fu_637_p3),64));
    zext_ln9_11_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln9_15_fu_649_p2),64));
    zext_ln9_1_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln5_reg_755),6));
    zext_ln9_2_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln5_fu_364_p3),5));
    zext_ln9_3_fu_457_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln9_8_fu_451_p2),64));
    zext_ln9_4_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln9_9_fu_490_p2),64));
    zext_ln9_5_fu_507_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln9_10_fu_501_p2),64));
    zext_ln9_6_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln9_11_fu_541_p2),64));
    zext_ln9_7_fu_557_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln9_12_fu_551_p2),64));
    zext_ln9_8_fu_587_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln9_13_fu_582_p2),64));
    zext_ln9_9_fu_597_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln9_14_fu_592_p2),64));
    zext_ln9_fu_538_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln5_reg_755),7));
end behav;
