// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.563000,HLS_SYN_LAT=502,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=211,HLS_SYN_LUT=964,HLS_VERSION=2024_1}" *)

module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        A_address1,
        A_ce1,
        A_q1,
        B_address0,
        B_ce0,
        B_q0,
        B_address1,
        B_ce1,
        B_q1,
        C_address0,
        C_ce0,
        C_we0,
        C_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] A_address0;
output   A_ce0;
input  [31:0] A_q0;
output  [6:0] A_address1;
output   A_ce1;
input  [31:0] A_q1;
output  [6:0] B_address0;
output   B_ce0;
input  [31:0] B_q0;
output  [6:0] B_address1;
output   B_ce1;
input  [31:0] B_q1;
output  [6:0] C_address0;
output   C_ce0;
output   C_we0;
output  [31:0] C_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_subdone;
wire   [0:0] icmp_ln5_fu_680_p2;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [31:0] grp_fu_313_p2;
reg   [31:0] reg_329;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_pp0_stage4_11001;
wire   [31:0] grp_fu_319_p2;
reg   [31:0] reg_333;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire   [3:0] select_ln5_fu_364_p3;
reg   [3:0] select_ln5_reg_755;
wire    ap_block_pp0_stage0_11001;
wire   [6:0] empty_6_fu_415_p1;
reg   [6:0] empty_6_reg_763;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [5:0] zext_ln9_1_fu_487_p1;
reg   [5:0] zext_ln9_1_reg_806;
wire   [31:0] add_ln9_fu_512_p2;
reg   [31:0] add_ln9_reg_821;
wire   [6:0] zext_ln9_fu_538_p1;
reg   [6:0] zext_ln9_reg_836;
wire   [31:0] add_ln9_2_fu_608_p2;
reg   [31:0] add_ln9_2_reg_874;
wire   [6:0] add_ln11_fu_659_p2;
reg   [6:0] add_ln11_reg_899;
reg   [31:0] mul_ln9_4_reg_904;
wire   [0:0] icmp_ln6_fu_674_p2;
reg   [0:0] icmp_ln6_reg_909;
reg   [0:0] icmp_ln5_reg_914;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_icmp_ln64_phi_fu_306_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] p_cast7_fu_410_p1;
wire   [63:0] tmp_1_cast_fu_437_p1;
wire   [63:0] zext_ln6_fu_442_p1;
wire   [63:0] zext_ln9_3_fu_457_p1;
wire   [63:0] p_cast8_fu_472_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] p_cast9_fu_482_p1;
wire   [63:0] zext_ln9_4_fu_496_p1;
wire   [63:0] zext_ln9_5_fu_507_p1;
wire   [63:0] p_cast10_fu_523_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] p_cast11_fu_533_p1;
wire   [63:0] zext_ln9_6_fu_546_p1;
wire   [63:0] zext_ln9_7_fu_557_p1;
wire   [63:0] p_cast12_fu_567_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] p_cast13_fu_577_p1;
wire   [63:0] zext_ln9_8_fu_587_p1;
wire   [63:0] zext_ln9_9_fu_597_p1;
wire   [63:0] p_cast14_fu_622_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] p_cast15_fu_632_p1;
wire   [63:0] zext_ln9_10_fu_644_p1;
wire   [63:0] zext_ln9_11_fu_654_p1;
wire   [63:0] zext_ln11_fu_696_p1;
reg   [6:0] indvar_flatten1_fu_100;
wire   [6:0] add_ln5_1_fu_668_p2;
reg   [3:0] i2_fu_104;
wire   [3:0] i_fu_372_p3;
reg   [3:0] ap_sig_allocacmp_i2_load;
reg   [3:0] j3_fu_108;
wire   [3:0] j_fu_663_p2;
reg   [3:0] ap_sig_allocacmp_j3_load;
reg    A_ce1_local;
reg   [6:0] A_address1_local;
reg    A_ce0_local;
reg   [6:0] A_address0_local;
reg    B_ce1_local;
reg   [6:0] B_address1_local;
reg    B_ce0_local;
reg   [6:0] B_address0_local;
reg    C_we0_local;
wire   [31:0] sum_fu_727_p2;
reg    C_ce0_local;
reg  signed [31:0] grp_fu_313_p0;
reg  signed [31:0] grp_fu_313_p1;
reg  signed [31:0] grp_fu_319_p0;
reg  signed [31:0] grp_fu_319_p1;
wire   [3:0] add_ln5_fu_358_p2;
wire   [6:0] tmp_fu_380_p3;
wire   [4:0] tmp_2_fu_392_p3;
wire   [7:0] p_shl_fu_388_p1;
wire   [7:0] p_shl43_fu_400_p1;
wire   [7:0] empty_fu_404_p2;
wire   [5:0] tmp_cast_fu_419_p4;
wire   [6:0] tmp_1_fu_429_p3;
wire   [4:0] zext_ln9_2_fu_447_p1;
wire   [4:0] add_ln9_8_fu_451_p2;
wire   [6:0] empty_7_fu_467_p2;
wire   [6:0] empty_8_fu_477_p2;
wire   [5:0] add_ln9_9_fu_490_p2;
wire   [5:0] add_ln9_10_fu_501_p2;
wire   [6:0] empty_9_fu_518_p2;
wire   [6:0] empty_10_fu_528_p2;
wire   [5:0] add_ln9_11_fu_541_p2;
wire   [6:0] add_ln9_12_fu_551_p2;
wire   [6:0] empty_11_fu_562_p2;
wire   [6:0] empty_12_fu_572_p2;
wire   [6:0] add_ln9_13_fu_582_p2;
wire   [6:0] add_ln9_14_fu_592_p2;
wire   [31:0] add_ln9_1_fu_602_p2;
wire   [6:0] empty_13_fu_617_p2;
wire   [6:0] empty_14_fu_627_p2;
wire   [6:0] tmp_2_cast_fu_637_p3;
wire   [6:0] add_ln9_15_fu_649_p2;
wire   [31:0] add_ln9_5_fu_710_p2;
wire   [31:0] add_ln9_6_fu_716_p2;
wire   [31:0] add_ln9_4_fu_704_p2;
wire   [31:0] add_ln9_7_fu_721_p2;
wire   [31:0] add_ln9_3_fu_700_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_635;
reg    ap_condition_251;
reg    ap_condition_640;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 indvar_flatten1_fu_100 = 7'd0;
#0 i2_fu_104 = 4'd0;
#0 j3_fu_108 = 4'd0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U1(
    .din0(grp_fu_313_p0),
    .din1(grp_fu_313_p1),
    .dout(grp_fu_313_p2)
);

matrix_mult_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U2(
    .din0(grp_fu_319_p0),
    .din1(grp_fu_319_p1),
    .dout(grp_fu_319_p2)
);

matrix_mult_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0)))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_251)) begin
        i2_fu_104 <= i_fu_372_p3;
    end
end

always @ (posedge ap_clk) begin
if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
    if ((1'b1 == ap_condition_640)) begin
        indvar_flatten1_fu_100 <= 7'd0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        indvar_flatten1_fu_100 <= add_ln5_1_fu_668_p2;
    end
end
end

always @ (posedge ap_clk) begin
if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
    if ((1'b1 == ap_condition_640)) begin
        j3_fu_108 <= 4'd0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        j3_fu_108 <= j_fu_663_p2;
    end
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        add_ln11_reg_899 <= add_ln11_fu_659_p2;
        icmp_ln5_reg_914 <= icmp_ln5_fu_680_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln9_2_reg_874 <= add_ln9_2_fu_608_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln9_reg_821 <= add_ln9_fu_512_p2;
        zext_ln9_1_reg_806[3 : 0] <= zext_ln9_1_fu_487_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_6_reg_763[6 : 1] <= empty_6_fu_415_p1[6 : 1];
        select_ln5_reg_755 <= select_ln5_fu_364_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        icmp_ln6_reg_909 <= icmp_ln6_fu_674_p2;
        mul_ln9_4_reg_904 <= grp_fu_319_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_329 <= grp_fu_313_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_333 <= grp_fu_319_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        zext_ln9_reg_836[3 : 0] <= zext_ln9_fu_538_p1[3 : 0];
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            A_address0_local = p_cast15_fu_632_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            A_address0_local = p_cast13_fu_577_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            A_address0_local = p_cast11_fu_533_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            A_address0_local = p_cast9_fu_482_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            A_address0_local = tmp_1_cast_fu_437_p1;
        end else begin
            A_address0_local = 'bx;
        end
    end else begin
        A_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            A_address1_local = p_cast14_fu_622_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            A_address1_local = p_cast12_fu_567_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            A_address1_local = p_cast10_fu_523_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            A_address1_local = p_cast8_fu_472_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            A_address1_local = p_cast7_fu_410_p1;
        end else begin
            A_address1_local = 'bx;
        end
    end else begin
        A_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        A_ce0_local = 1'b1;
    end else begin
        A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        A_ce1_local = 1'b1;
    end else begin
        A_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            B_address0_local = zext_ln9_11_fu_654_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            B_address0_local = zext_ln9_9_fu_597_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            B_address0_local = zext_ln9_7_fu_557_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            B_address0_local = zext_ln9_5_fu_507_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            B_address0_local = zext_ln9_3_fu_457_p1;
        end else begin
            B_address0_local = 'bx;
        end
    end else begin
        B_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            B_address1_local = zext_ln9_10_fu_644_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            B_address1_local = zext_ln9_8_fu_587_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            B_address1_local = zext_ln9_6_fu_546_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            B_address1_local = zext_ln9_4_fu_496_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            B_address1_local = zext_ln6_fu_442_p1;
        end else begin
            B_address1_local = 'bx;
        end
    end else begin
        B_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        B_ce0_local = 1'b1;
    end else begin
        B_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        B_ce1_local = 1'b1;
    end else begin
        B_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_ce0_local = 1'b1;
    end else begin
        C_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_we0_local = 1'b1;
    end else begin
        C_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln5_fu_680_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln5_reg_914 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_635)) begin
            ap_phi_mux_icmp_ln64_phi_fu_306_p4 = icmp_ln6_reg_909;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln64_phi_fu_306_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln64_phi_fu_306_p4 = icmp_ln6_reg_909;
        end
    end else begin
        ap_phi_mux_icmp_ln64_phi_fu_306_p4 = icmp_ln6_reg_909;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i2_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i2_load = i2_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j3_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j3_load = j3_fu_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_313_p0 = B_q0;
    end else if ((((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_313_p0 = B_q1;
    end else begin
        grp_fu_313_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_313_p1 = A_q0;
    end else if ((((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_313_p1 = A_q1;
    end else begin
        grp_fu_313_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_319_p0 = B_q1;
    end else if ((((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_319_p0 = B_q0;
    end else begin
        grp_fu_319_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_319_p1 = A_q1;
    end else if ((((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_319_p1 = A_q0;
    end else begin
        grp_fu_319_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = A_address0_local;

assign A_address1 = A_address1_local;

assign A_ce0 = A_ce0_local;

assign A_ce1 = A_ce1_local;

assign B_address0 = B_address0_local;

assign B_address1 = B_address1_local;

assign B_ce0 = B_ce0_local;

assign B_ce1 = B_ce1_local;

assign C_address0 = zext_ln11_fu_696_p1;

assign C_ce0 = C_ce0_local;

assign C_d0 = sum_fu_727_p2;

assign C_we0 = C_we0_local;

assign add_ln11_fu_659_p2 = (empty_6_reg_763 + zext_ln9_reg_836);

assign add_ln5_1_fu_668_p2 = (indvar_flatten1_fu_100 + 7'd1);

assign add_ln5_fu_358_p2 = (ap_sig_allocacmp_i2_load + 4'd1);

assign add_ln9_10_fu_501_p2 = (zext_ln9_1_fu_487_p1 + 6'd30);

assign add_ln9_11_fu_541_p2 = ($signed(zext_ln9_1_reg_806) + $signed(6'd40));

assign add_ln9_12_fu_551_p2 = (zext_ln9_fu_538_p1 + 7'd50);

assign add_ln9_13_fu_582_p2 = (zext_ln9_reg_836 + 7'd60);

assign add_ln9_14_fu_592_p2 = ($signed(zext_ln9_reg_836) + $signed(7'd70));

assign add_ln9_15_fu_649_p2 = ($signed(zext_ln9_reg_836) + $signed(7'd90));

assign add_ln9_1_fu_602_p2 = (reg_333 + grp_fu_313_p2);

assign add_ln9_2_fu_608_p2 = (add_ln9_1_fu_602_p2 + reg_329);

assign add_ln9_3_fu_700_p2 = (add_ln9_2_reg_874 + add_ln9_reg_821);

assign add_ln9_4_fu_704_p2 = (reg_333 + reg_329);

assign add_ln9_5_fu_710_p2 = (grp_fu_319_p2 + grp_fu_313_p2);

assign add_ln9_6_fu_716_p2 = (add_ln9_5_fu_710_p2 + mul_ln9_4_reg_904);

assign add_ln9_7_fu_721_p2 = (add_ln9_6_fu_716_p2 + add_ln9_4_fu_704_p2);

assign add_ln9_8_fu_451_p2 = (zext_ln9_2_fu_447_p1 + 5'd10);

assign add_ln9_9_fu_490_p2 = (zext_ln9_1_fu_487_p1 + 6'd20);

assign add_ln9_fu_512_p2 = (grp_fu_319_p2 + grp_fu_313_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_251 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_635 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln5_reg_914 == 1'd0));
end

always @ (*) begin
    ap_condition_640 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

assign ap_ready = ap_ready_sig;

assign empty_10_fu_528_p2 = (empty_6_reg_763 + 7'd5);

assign empty_11_fu_562_p2 = (empty_6_reg_763 + 7'd6);

assign empty_12_fu_572_p2 = (empty_6_reg_763 + 7'd7);

assign empty_13_fu_617_p2 = (empty_6_reg_763 + 7'd8);

assign empty_14_fu_627_p2 = (empty_6_reg_763 + 7'd9);

assign empty_6_fu_415_p1 = empty_fu_404_p2[6:0];

assign empty_7_fu_467_p2 = (empty_6_reg_763 + 7'd2);

assign empty_8_fu_477_p2 = (empty_6_reg_763 + 7'd3);

assign empty_9_fu_518_p2 = (empty_6_reg_763 + 7'd4);

assign empty_fu_404_p2 = (p_shl_fu_388_p1 + p_shl43_fu_400_p1);

assign i_fu_372_p3 = ((ap_phi_mux_icmp_ln64_phi_fu_306_p4[0:0] == 1'b1) ? add_ln5_fu_358_p2 : ap_sig_allocacmp_i2_load);

assign icmp_ln5_fu_680_p2 = ((indvar_flatten1_fu_100 == 7'd99) ? 1'b1 : 1'b0);

assign icmp_ln6_fu_674_p2 = ((j_fu_663_p2 == 4'd10) ? 1'b1 : 1'b0);

assign j_fu_663_p2 = (select_ln5_reg_755 + 4'd1);

assign p_cast10_fu_523_p1 = empty_9_fu_518_p2;

assign p_cast11_fu_533_p1 = empty_10_fu_528_p2;

assign p_cast12_fu_567_p1 = empty_11_fu_562_p2;

assign p_cast13_fu_577_p1 = empty_12_fu_572_p2;

assign p_cast14_fu_622_p1 = empty_13_fu_617_p2;

assign p_cast15_fu_632_p1 = empty_14_fu_627_p2;

assign p_cast7_fu_410_p1 = empty_fu_404_p2;

assign p_cast8_fu_472_p1 = empty_7_fu_467_p2;

assign p_cast9_fu_482_p1 = empty_8_fu_477_p2;

assign p_shl43_fu_400_p1 = tmp_2_fu_392_p3;

assign p_shl_fu_388_p1 = tmp_fu_380_p3;

assign select_ln5_fu_364_p3 = ((ap_phi_mux_icmp_ln64_phi_fu_306_p4[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_j3_load);

assign sum_fu_727_p2 = (add_ln9_7_fu_721_p2 + add_ln9_3_fu_700_p2);

assign tmp_1_cast_fu_437_p1 = tmp_1_fu_429_p3;

assign tmp_1_fu_429_p3 = {{tmp_cast_fu_419_p4}, {1'd1}};

assign tmp_2_cast_fu_637_p3 = {{3'd5}, {select_ln5_reg_755}};

assign tmp_2_fu_392_p3 = {{i_fu_372_p3}, {1'd0}};

assign tmp_cast_fu_419_p4 = {{empty_fu_404_p2[6:1]}};

assign tmp_fu_380_p3 = {{i_fu_372_p3}, {3'd0}};

assign zext_ln11_fu_696_p1 = add_ln11_reg_899;

assign zext_ln6_fu_442_p1 = select_ln5_fu_364_p3;

assign zext_ln9_10_fu_644_p1 = tmp_2_cast_fu_637_p3;

assign zext_ln9_11_fu_654_p1 = add_ln9_15_fu_649_p2;

assign zext_ln9_1_fu_487_p1 = select_ln5_reg_755;

assign zext_ln9_2_fu_447_p1 = select_ln5_fu_364_p3;

assign zext_ln9_3_fu_457_p1 = add_ln9_8_fu_451_p2;

assign zext_ln9_4_fu_496_p1 = add_ln9_9_fu_490_p2;

assign zext_ln9_5_fu_507_p1 = add_ln9_10_fu_501_p2;

assign zext_ln9_6_fu_546_p1 = add_ln9_11_fu_541_p2;

assign zext_ln9_7_fu_557_p1 = add_ln9_12_fu_551_p2;

assign zext_ln9_8_fu_587_p1 = add_ln9_13_fu_582_p2;

assign zext_ln9_9_fu_597_p1 = add_ln9_14_fu_592_p2;

assign zext_ln9_fu_538_p1 = select_ln5_reg_755;

always @ (posedge ap_clk) begin
    empty_6_reg_763[0] <= 1'b0;
    zext_ln9_1_reg_806[5:4] <= 2'b00;
    zext_ln9_reg_836[6:4] <= 3'b000;
end

endmodule //matrix_mult
